### ISSUE TITLE
apparenty Applicative and Foldable are missing during building. ghc version 8.0.2

### ISSUE THREAD

**Issue by SaverioFrancesco** [miniBill/entangle#1]

**Comment by miniBill** [comment]
PRs are welcome. Also, try building with stack. Sorry for the short answer but no time =)

**Comment by SaverioFrancesco** [comment]
yes with stcak I had no problem! thank you!

**Comment by SaverioFrancesco** [comment]
Note: do not use cabal alone to get tis project. It will get you only building errors. Instead clone it and use stack setup || stack install
